kind: Service
apiVersion: v1
metadata:
  name: fdt-service
spec:
  type: NodePort
  selector:
    app: fdt
  ports:
      - targetPort: 3000
        port: 3000
        nodePort: 32322
---
apiVersion: v1
kind: Pod
metadata:
  name: fdt
  labels:
      name: fdt
      app: fdt
spec:
  volumes:
      - name: volume
        hostPath:
          path: /data/dtn/perftests
  nodeSelector:
      type: dtn
  containers:
      - image: recap/process-fdt:v0.1
        name: fdt
        ports:
            - containerPort: 3000
        command: ["/bin/bash", "-c"]
        args: ["cd /app/ && bash server 3000"]
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /data
          name: volume

